dist: xenial
script: "/bin/true"
notifications:
  email: false
  slack:
    secure: X8DkSsFzI+DPiCBIHow3321VNiV+Tap66oRVMqwhtVIE1IJojf2eLbw53Km3NUvFgqnKtxLSSDl3cGP2PZoKp22AuAtde8Nk06zhf0272kx4asdxfmJP6otYDRdDCySRHrb47p60q0am5KT74ZIv6eTQQj3QMMGLiX9Ewtc6EXPJEBRThh9I1ijWXPuwYHED9IaFtqQkFCCjoeTe0CJ1UtXdJF0j2h325AEJlyEpy9uP9JcvFEQKyvQkL69MvlNasNgfpUC/wjRXF5/yQL7iVKe+37KHiiQ3KQffsYEopuuDYYiCZvN7UA633Li8TQyY9kfiIHJGR50rs0bVCaaOafc+u3V730TCj+61zmQt/NI0kcJIqtcaT24aAKWFrA+1sBLlPvqa9Po7ij20m50O2OjQEbS2enmgTlDQz99r5VKnU8pJswrsxaBP/+8hX3O5VNhxsn3MwDRdrzPrDdXUgnrRxTg+irprl5eOqcfSESsbvsgOu1Kk6pxAnGjZVM/g+tZOnBVEBPQ84E2LIzqYQ0flmLzoqEYyahMwxfnuh+0paJJgz9Fuu2Kk8AP3yVf7guZuEy4tp4Cdec2WfU5ALQNLJ/uco7TvVVFoCKLPIM/1h68mcCS5GvXKtPMb5R0aZmZbMSlYfF16HgK/oZJlDx9pOtB8qfy7sKtLgFTG0+s=
